{{ if .Values.ingress.route.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-route
  labels:
    app: {{ .Release.Name }}-route
spec:
  selector:
    app: {{ .Release.Name }}-route
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: {{ .Values.ingress.route.serviceType }}
{{ end }}