name: Bug Report
description: Create a bug report to help improve Kyoo
labels: [bug]
body:
  - type: input
    attributes:
      label: "Kyoo's version"
  - type: textarea
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
