#!/bin/sh
set -e

sudo -u postgres psql << "EOF"
DO $$
BEGIN
  CREATE ROLE kyoo WITH CREATEDB LOGIN PASSWORD 'kyooPassword';
  EXCEPTION WHEN DUPLICATE_OBJECT THEN
  RAISE NOTICE 'not creating role kyoo -- it already exists';
END
$$;
EOF

systemd-sysusers
systemd-tmpfiles --create
