export enum Genre {
	Action = "Action",
	Adventure = "Adventure",
	Animation = "Animation",
	Comedy = "Comedy",
	Crime = "Crime",
	Documentary = "Documentary",
	Drama = "Drama",
	Family = "Family",
	Fantasy = "Fantasy",
	History = "History",
	Horror = "Horror",
	Music = "Music",
	Mystery = "Mystery",
	Romance = "Romance",
	ScienceFiction = "ScienceFiction",
	Thriller = "Thriller",
	War = "War",
	Western = "Western",
	Kids = "Kids",
	News = "News",
	Reality = "Reality",
	Soap = "Soap",
	Talk = "Talk",
	Politics = "Politics",
}
