FROM ghcr.io/zoriya/ffmpeg:v8.0.4-dev

COPY --from=golang:1.26 /usr/local/go /usr/local/go
ENV PATH="/usr/local/go/bin:${PATH}"
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
# create a cache in the image so hot-reload is fast (incremental)
RUN go build -race -o /dev/null .

# flags for nvidia acceleration on docker < 25.0
ENV NVIDIA_VISIBLE_DEVICES="all"
ENV NVIDIA_DRIVER_CAPABILITIES="all"

EXPOSE 7666
CMD ["go", "run", "-race", "."]
