// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dbc

import (
	"time"

	jwt "github.com/golang-jwt/jwt/v5"
	"github.com/google/uuid"
)

type Config struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type OidcHandle struct {
	UserPk       int32      `json:"userPk"`
	Provider     string     `json:"provider"`
	Id           string     `json:"id"`
	Username     string     `json:"username"`
	ProfileUrl   *string    `json:"profileUrl"`
	AccessToken  *string    `json:"accessToken"`
	RefreshToken *string    `json:"refreshToken"`
	ExpireAt     *time.Time `json:"expireAt"`
}

type Session struct {
	Pk          int32     `json:"pk"`
	Id          uuid.UUID `json:"id"`
	Token       string    `json:"token"`
	UserPk      int32     `json:"userPk"`
	CreatedDate time.Time `json:"createdDate"`
	LastUsed    time.Time `json:"lastUsed"`
	Device      *string   `json:"device"`
}

type User struct {
	Pk          int32         `json:"pk"`
	Id          uuid.UUID     `json:"id"`
	Username    string        `json:"username"`
	Email       string        `json:"email"`
	Password    *string       `json:"password"`
	Claims      jwt.MapClaims `json:"claims"`
	CreatedDate time.Time     `json:"createdDate"`
	LastSeen    time.Time     `json:"lastSeen"`
}
