apiVersion: apps/v1
kind: Deployment
metadata:
  {{- if and (.Values.global.podAnnotations) (.Values.scanner.deploymentAnnotations) }}
    {{- with (mergeOverwrite (deepCopy .Values.global.deploymentAnnotations) .Values.scanner.deploymentAnnotations) }}
  annotations:
      {{- range $key, $value := . }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
    {{- end }}
  {{- end }}
  name: {{ include "kyoo.scanner.fullname" . }}
  labels:
    {{- include "kyoo.labels" (dict "context" . "component" .Values.scanner.name "name" .Values.scanner.name) | nindent 4 }}
spec:
  replicas: {{ .Values.scanner.replicaCount }}
  strategy:
    {{- toYaml .Values.scanner.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "kyoo.selectorLabels" (dict "context" . "name" .Values.scanner.name) | nindent 6 }}
  template:
    metadata:
      {{- if (and .Values.global.podAnnotations .Values.scanner.podAnnotations) }}
      annotations:
        {{- with (mergeOverwrite (deepCopy .Values.global.podAnnotations) .Values.scanner.podAnnotations) }}
          {{- range $key, $value := . }}
            {{ $key }}: {{ $value | quote }}
          {{- end }}
        {{- end }}
      {{- end }}
      labels:
        {{- include "kyoo.labels" (dict "context" . "component" .Values.scanner.name "name" .Values.scanner.name) | nindent 8 }}
        {{- with (mergeOverwrite (deepCopy .Values.global.podLabels) .Values.scanner.podLabels) }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.scanner.imagePullSecrets | default .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scanner.kyoo_scanner.containerSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kyoo.scanner.serviceAccountName" . }}
      containers:
        - name: main
          image: {{ .Values.scanner.kyoo_scanner.image.repository | default (printf "%s/kyoo_scanner" .Values.global.image.repositoryBase) }}:{{ default (include "kyoo.defaultTag" .) .Values.scanner.kyoo_scanner.image.tag }}
          imagePullPolicy: {{ default .Values.global.image.imagePullPolicy }}
          {{- if .Values.scanner.kyoo_scanner.extraArgs }}
          args:
            {{- with .Values.scanner.kyoo_scanner.extraArgs }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          env:
            - name: SCANNER_LIBRARY_ROOT
              value: {{ .Values.volumes.media.mountPath | quote }}
            - name: LIBRARY_IGNORE_PATTERN
              value: {{ .Values.kyoo.libraryIgnorePattern | quote }}
            - name: KYOO_APIKEYS
              {{- if .Values.kyoo.existingSecret.name }}
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.kyoo.existingSecret.key }}
                  name: {{ .Values.kyoo.existingSecret.name }}
              {{- else }}
              value: {{ .Values.kyoo.apikey }}
              {{- end }}
            - name: KYOO_URL
              value: "http://{{ include "kyoo.back.fullname" . }}:5000"
            - name: LIBRARY_LANGUAGES
              value: {{ .Values.kyoo.languages | quote }}
            - name: RABBITMQ_HOST
              value: {{ .Values.rabbitmq.host | quote }}
            - name: RABBITMQ_PORT
              value: {{ .Values.rabbitmq.port | quote }}
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.rabbitmq.kyoo_scanner.userKey }}
                  name: {{ .Values.rabbitmq.kyoo_scanner.existingSecret }}
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.rabbitmq.kyoo_scanner.passwordKey }}
                  name: {{ .Values.rabbitmq.kyoo_scanner.existingSecret }}
            {{- with (concat .Values.global.extraEnv .Values.scanner.kyoo_scanner.extraEnv) }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.scanner.kyoo_scanner.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.scanner.kyoo_scanner.livenessProbe | nindent 12 }}
          {{- end }}
          {{- with .Values.scanner.kyoo_scanner.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.scanner.kyoo_scanner.readinessProbe | nindent 12 }}
          {{- end }}
          {{- with .Values.scanner.kyoo_scanner.resources }}
          resources:
            {{- toYaml .Values.scanner.kyoo_scanner.resources | nindent 12 }}
          {{- end }}
          {{- with .Values.scanner.kyoo_scanner.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: media
              mountPath: {{ .Values.volumes.media.mountPath }}
            {{- with .Values.scanner.kyoo_scanner.extraVolumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- with .Values.scanner.extraContainers }}
          {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
      {{- with .Values.scanner.extraInitContainers }}
      initContainers:
        {{- tpl (toYaml .) $ | nindent 6 }}
      {{- end }}
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-media
        {{- with .Values.scanner.extraVolumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}