name: Coding Style
on: [pull_request, workflow_dispatch]

jobs:
  api:
    name: "Lint api"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v6

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome
        run: biome ci .

  front:
    name: "Lint Front"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      - uses: actions/checkout@v6

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome
        run: biome ci .

  typecheck-api:
    name: "Typecheck api"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Typecheck
        run: bun run typecheck

  typecheck-front:
    name: "Typecheck front"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      - uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Typecheck
        run: bun run typecheck

  scanner:
    name: "Lint scanner"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: chartboost/ruff-action@v1
        with:
          args: format --check

  transcoder:
    name: "Lint transcoder"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./transcoder
    steps:
      - uses: actions/checkout@v6

      - name: Run go fmt
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

  auth:
    name: "Lint auth"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./auth
    steps:
      - uses: actions/checkout@v6

      - name: Run go fmt
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
