name: RobotTests
on:
  push:
    branches:
      - master
      - next
  pull_request:


jobs:
  test:
    name: Robot tests Auth
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
         - "5432:5432"
        env:
          POSTGRES_USER: kyoo
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - name: Robot cache
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - run: pip install -r requirements.txt

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.22.5'
          cache-dependency-path: ./auth/go.sum

      - name: Install dependencies
        working-directory: ./auth
        run: |
          go mod download
          go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
          go install github.com/swaggo/swag/cmd/swag@latest

      - name: Build
        working-directory: ./auth
        run: |
          sqlc generate
          swag init --parseDependency
          go build -o ./keibi

      - name: Run robot tests
        working-directory: ./auth
        run: |
          ./keibi > logs &
          wget --retry-connrefused --retry-on-http-error=502 http://localhost:4568/health
          robot -d out robot
        env:
          POSTGRES_SERVER: localhost

      - name: Show logs
        working-directory: ./auth
        run: cat logs

      - uses: actions/upload-artifact@v4
        with:
          name: results
          path: auth/out

